[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "groq>=1.4.0",
    "langchain-text-splitters>=1.1.2",
    "openai>=2.41.1",
    "pdfplumber>=0.11.10",
    "requests>=2.34.2",
    "uvicorn>=0.48.0",
]
